//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markuse_arvuti_integratsioonitarkvara.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Markuse_arvuti_integratsioonitarkvara.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] br {
            get {
                object obj = ResourceManager.GetObject("br", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] failure {
            get {
                object obj = ResourceManager.GetObject("failure", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] folder1 {
            get {
                object obj = ResourceManager.GetObject("folder1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] MarkuStation_awesome {
            get {
                object obj = ResourceManager.GetObject("MarkuStation_awesome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_computers {
            get {
                object obj = ResourceManager.GetObject("mas_computers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_flash {
            get {
                object obj = ResourceManager.GetObject("mas_flash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_gadgets {
            get {
                object obj = ResourceManager.GetObject("mas_gadgets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_general {
            get {
                object obj = ResourceManager.GetObject("mas_general", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_its_symmetric {
            get {
                object obj = ResourceManager.GetObject("mas_its_symmetric", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_optical {
            get {
                object obj = ResourceManager.GetObject("mas_optical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_sync {
            get {
                object obj = ResourceManager.GetObject("mas_sync", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_virtualpc {
            get {
                object obj = ResourceManager.GetObject("mas_virtualpc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_vpc {
            get {
                object obj = ResourceManager.GetObject("mas_vpc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_tablet {
            get {
                object obj = ResourceManager.GetObject("mas_tablet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_vpc_full {
            get {
                object obj = ResourceManager.GetObject("mas_vpc_full", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mas_web {
            get {
                object obj = ResourceManager.GetObject("mas_web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] noteicon {
            get {
                object obj = ResourceManager.GetObject("noteicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] pending {
            get {
                object obj = ResourceManager.GetObject("pending", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] root_idc_key {
            get {
                object obj = ResourceManager.GetObject("root_idc_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] theming {
            get {
                object obj = ResourceManager.GetObject("theming", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] user_black {
            get {
                object obj = ResourceManager.GetObject("user_black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] user_blue {
            get {
                object obj = ResourceManager.GetObject("user_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] pidu {
            get {
                object obj = ResourceManager.GetObject("pidu", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
